In [7]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
train_data = pd.read_csv('train_modified_data.csv')

In [9]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 30 columns):
Unnamed: 0                      891 non-null int64
PassengerId                     891 non-null int64
Survived                        891 non-null int64
first_class                     891 non-null int64
second_class                    891 non-null int64
third_class                     891 non-null int64
female                          891 non-null int64
male                            891 non-null int64
adult                           891 non-null int64
infant                          891 non-null int64
old                             891 non-null int64
teenage                         891 non-null int64
alphanum_ticket                 891 non-null int64
character_ticket                891 non-null int64
decimal_ticket                  891 non-null int64
Class_Fare_first_class_fare     891 non-null int64
Class_Fare_second_class_fare    891 non-null int64
Class_Fare_third_class_fare     891 non-null int64
Cab_Class_A_deck                891 non-null int64
Cab_Class_B_deck                891 non-null int64
Cab_Class_C_deck                891 non-null int64
Cab_Class_D_deck                891 non-null int64
Cab_Class_E_deck                891 non-null int64
Cab_Class_F_deck                891 non-null int64
Cab_Class_G_deck                891 non-null int64
Cab_Class_low_deck              891 non-null int64
C                               891 non-null int64
No Embarked                     891 non-null int64
Q                               891 non-null int64
S                               891 non-null int64
dtypes: int64(30)
memory usage: 209.0 KB

In [10]:
train_data.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'first_class', 'second_class',
       'third_class', 'female', 'male', 'adult', 'infant', 'old', 'teenage',
       'alphanum_ticket', 'character_ticket', 'decimal_ticket',
       'Class_Fare_first_class_fare', 'Class_Fare_second_class_fare',
       'Class_Fare_third_class_fare', 'Cab_Class_A_deck', 'Cab_Class_B_deck',
       'Cab_Class_C_deck', 'Cab_Class_D_deck', 'Cab_Class_E_deck',
       'Cab_Class_F_deck', 'Cab_Class_G_deck', 'Cab_Class_low_deck', 'C',
       'No Embarked', 'Q', 'S'],
      dtype='object')

In [15]:
train_data.drop(['Unnamed: 0'], inplace=True, axis=1)

In [16]:
train_data.columns

Index(['PassengerId', 'Survived', 'first_class', 'second_class', 'third_class',
       'female', 'male', 'adult', 'infant', 'old', 'teenage',
       'alphanum_ticket', 'character_ticket', 'decimal_ticket',
       'Class_Fare_first_class_fare', 'Class_Fare_second_class_fare',
       'Class_Fare_third_class_fare', 'Cab_Class_A_deck', 'Cab_Class_B_deck',
       'Cab_Class_C_deck', 'Cab_Class_D_deck', 'Cab_Class_E_deck',
       'Cab_Class_F_deck', 'Cab_Class_G_deck', 'Cab_Class_low_deck', 'C',
       'No Embarked', 'Q', 'S'],
      dtype='object')

In [22]:
#import splitting and testing package
x = train_data[['first_class', 'second_class', 'third_class', 'female', 'male', 'adult', 'infant', 'old', 'teenage',\
               'alphanum_ticket', 'character_ticket', 'decimal_ticket',  'Class_Fare_first_class_fare', 'Class_Fare_second_class_fare',\
               'Class_Fare_third_class_fare', 'Cab_Class_A_deck', 'Cab_Class_B_deck', 'Cab_Class_C_deck', 'Cab_Class_D_deck', 'Cab_Class_E_deck',\
               'Cab_Class_F_deck', 'Cab_Class_G_deck', 'Cab_Class_low_deck', 'C', 'No Embarked', 'Q', 'S']]
y = train_data['Survived']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [23]:
#import Lgositic Regression
from sklearn.linear_model import LogisticRegression
LogML = LogisticRegression()

In [24]:
LogML.fit(x_train, y_train)

/home/wira/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
prediction = LogML.predict(x_test)

In [26]:
prediction

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0])

In [27]:
np.mean(prediction == y_test)

0.8340807174887892

In [28]:
x_test

,first_class,second_class,third_class,female,male,adult,infant,old,teenage,alphanum_ticket,...,Cab_Class_C_deck,Cab_Class_D_deck,Cab_Class_E_deck,Cab_Class_F_deck,Cab_Class_G_deck,Cab_Class_low_deck,C,No Embarked,Q,S
537,1,0,0,1,0,1,0,0,0,1,...,0,0,0,0,0,1,1,0,0,0
552,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
87,0,0,1,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
211,0,1,0,1,0,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
658,0,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
158,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
427,0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
227,0,0,1,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
357,0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
719,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
690,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
176,0,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
540,1,0,0,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
94,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1
410,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
646,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
20,0,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
350,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
417,0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
786,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
281,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
255,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
90,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
315,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
185,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
327,0,1,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
251,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
632,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
652,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
763,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
48,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
747,0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
761,0,0,1,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
867,1,0,0,0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
820,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
600,0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
842,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
364,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
770,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
454,0,0,1,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
837,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
385,0,1,0,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
869,0,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
273,1,0,0,0,1,1,0,0,0,1,...,1,0,0,0,0,0,1,0,0,0
96,1,0,0,0,1,0,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
46,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
317,0,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
616,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
265,0,1,0,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
402,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
83,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
882,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
115,0,0,1,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
486,1,0,0,1,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
161,0,1,0,1,0,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
239,0,1,0,0,1,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
1,1,0,0,1,0,1,0,0,0,1,...,1,0,0,0,0,0,1,0,0,0
391,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
163,0,0,1,0,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1

In [32]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 223 entries, 537 to 163
Data columns (total 27 columns):
first_class                     223 non-null int64
second_class                    223 non-null int64
third_class                     223 non-null int64
female                          223 non-null int64
male                            223 non-null int64
adult                           223 non-null int64
infant                          223 non-null int64
old                             223 non-null int64
teenage                         223 non-null int64
alphanum_ticket                 223 non-null int64
character_ticket                223 non-null int64
decimal_ticket                  223 non-null int64
Class_Fare_first_class_fare     223 non-null int64
Class_Fare_second_class_fare    223 non-null int64
Class_Fare_third_class_fare     223 non-null int64
Cab_Class_A_deck                223 non-null int64
Cab_Class_B_deck                223 non-null int64
Cab_Class_C_deck                223 non-null int64
Cab_Class_D_deck                223 non-null int64
Cab_Class_E_deck                223 non-null int64
Cab_Class_F_deck                223 non-null int64
Cab_Class_G_deck                223 non-null int64
Cab_Class_low_deck              223 non-null int64
C                               223 non-null int64
No Embarked                     223 non-null int64
Q                               223 non-null int64
S                               223 non-null int64
dtypes: int64(27)
memory usage: 48.8 KB

In [53]:
X_test_data = pd.read_csv('test_modified_data.csv')

In [54]:
X_test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 27 columns):
Unnamed: 0                      418 non-null int64
PassengerId                     418 non-null int64
first_class                     418 non-null int64
second_class                    418 non-null int64
third_class                     418 non-null int64
female                          418 non-null int64
male                            418 non-null int64
adult                           418 non-null int64
infant                          418 non-null int64
old                             418 non-null int64
teenage                         418 non-null int64
alphanum_ticket                 418 non-null int64
decimal_ticket                  418 non-null int64
Class_Fare_first_class_fare     418 non-null int64
Class_Fare_second_class_fare    418 non-null int64
Class_Fare_third_class_fare     418 non-null int64
Cab_Class_A_deck                418 non-null int64
Cab_Class_B_deck                418 non-null int64
Cab_Class_C_deck                418 non-null int64
Cab_Class_D_deck                418 non-null int64
Cab_Class_E_deck                418 non-null int64
Cab_Class_F_deck                418 non-null int64
Cab_Class_G_deck                418 non-null int64
Cab_Class_low_deck              418 non-null int64
C                               418 non-null int64
Q                               418 non-null int64
S                               418 non-null int64
dtypes: int64(27)
memory usage: 88.3 KB

In [55]:
PassID = X_test_data['PassengerId']

In [56]:
X_test_data.drop(['Unnamed: 0', 'PassengerId'], axis=1, inplace=True)

In [57]:
X_test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 25 columns):
first_class                     418 non-null int64
second_class                    418 non-null int64
third_class                     418 non-null int64
female                          418 non-null int64
male                            418 non-null int64
adult                           418 non-null int64
infant                          418 non-null int64
old                             418 non-null int64
teenage                         418 non-null int64
alphanum_ticket                 418 non-null int64
decimal_ticket                  418 non-null int64
Class_Fare_first_class_fare     418 non-null int64
Class_Fare_second_class_fare    418 non-null int64
Class_Fare_third_class_fare     418 non-null int64
Cab_Class_A_deck                418 non-null int64
Cab_Class_B_deck                418 non-null int64
Cab_Class_C_deck                418 non-null int64
Cab_Class_D_deck                418 non-null int64
Cab_Class_E_deck                418 non-null int64
Cab_Class_F_deck                418 non-null int64
Cab_Class_G_deck                418 non-null int64
Cab_Class_low_deck              418 non-null int64
C                               418 non-null int64
Q                               418 non-null int64
S                               418 non-null int64
dtypes: int64(25)
memory usage: 81.8 KB

In [58]:
x_test.columns

Index(['first_class', 'second_class', 'third_class', 'female', 'male', 'adult',
       'infant', 'old', 'teenage', 'alphanum_ticket', 'character_ticket',
       'decimal_ticket', 'Class_Fare_first_class_fare',
       'Class_Fare_second_class_fare', 'Class_Fare_third_class_fare',
       'Cab_Class_A_deck', 'Cab_Class_B_deck', 'Cab_Class_C_deck',
       'Cab_Class_D_deck', 'Cab_Class_E_deck', 'Cab_Class_F_deck',
       'Cab_Class_G_deck', 'Cab_Class_low_deck', 'C', 'No Embarked', 'Q', 'S'],
      dtype='object')

In [59]:
X_test_data.columns

Index(['first_class', 'second_class', 'third_class', 'female', 'male', 'adult',
       'infant', 'old', 'teenage', 'alphanum_ticket', 'decimal_ticket',
       'Class_Fare_first_class_fare', 'Class_Fare_second_class_fare',
       'Class_Fare_third_class_fare', 'Cab_Class_A_deck', 'Cab_Class_B_deck',
       'Cab_Class_C_deck', 'Cab_Class_D_deck', 'Cab_Class_E_deck',
       'Cab_Class_F_deck', 'Cab_Class_G_deck', 'Cab_Class_low_deck', 'C', 'Q',
       'S'],
      dtype='object')

In [61]:
X_test_data['No Embarked'] = 0

In [62]:
X_test_data['character_ticket'] = 0

In [63]:
X_test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 27 columns):
first_class                     418 non-null int64
second_class                    418 non-null int64
third_class                     418 non-null int64
female                          418 non-null int64
male                            418 non-null int64
adult                           418 non-null int64
infant                          418 non-null int64
old                             418 non-null int64
teenage                         418 non-null int64
alphanum_ticket                 418 non-null int64
decimal_ticket                  418 non-null int64
Class_Fare_first_class_fare     418 non-null int64
Class_Fare_second_class_fare    418 non-null int64
Class_Fare_third_class_fare     418 non-null int64
Cab_Class_A_deck                418 non-null int64
Cab_Class_B_deck                418 non-null int64
Cab_Class_C_deck                418 non-null int64
Cab_Class_D_deck                418 non-null int64
Cab_Class_E_deck                418 non-null int64
Cab_Class_F_deck                418 non-null int64
Cab_Class_G_deck                418 non-null int64
Cab_Class_low_deck              418 non-null int64
C                               418 non-null int64
Q                               418 non-null int64
S                               418 non-null int64
No Embarked                     418 non-null int64
character_ticket                418 non-null int64
dtypes: int64(27)
memory usage: 88.3 KB

In [64]:
first_prediction = LogML.predict(X_test_data)

In [65]:
first_prediction

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [66]:
first_predictionDF = pd.DataFrame(columns=['PassengerId', 'Survived'])

In [67]:
first_predictionDF['PassengerId'] = PassID

In [68]:
first_predictionDF['Survived'] = first_prediction

In [69]:
first_predictionDF.to_csv('myTitanicprediction.csv')

In [70]:
first_predictionDF.columns

Index(['PassengerId', 'Survived'], dtype='object')

In [71]:
first_predictionDF.iloc[0]

PassengerId    892
Survived         0
Name: 0, dtype: int64

In [72]:
PassID

0       892
1       893
2       894
3       895
4       896
       ...
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64

In [73]:
first_predictionDF.index

RangeIndex(start=0, stop=418, step=1)